[package]
name = "lull-spec"
version = "0.1.0"
edition = "2024"
authors = ["WatchDG <baranov@w3m.co>"]
description = "Lull spec library"
license = "MIT"
repository = "https://github.com/WatchDG/rust-lull-spec"
homepage = "https://github.com/WatchDG/rust-lull-spec"
documentation = "https://docs.rs/lull-spec"
keywords = ["lull", "spec"]
categories = ["data-structures"]

[dependencies]
